import { useSelector } from "react-redux";

const useTranslate = () => {
  const { currectLanguage } = useSelector((state) => state.language);

  const englishToBangla = {
    Home: "হোম",
    Student: "ছাত্র-ছাত্রী",
    "Book List": "বুক লিস্ট",
    Staff: "স্টাফ",
    Exam: "পরীক্ষা",
    Libery: "লাইব্রেরি",
    Others: "অন্যান্য",
    Setting: "সেটিংস",
    "Sahara IT": "সাহারা আইটি",
    Sahara: "সাহারা",
    IT: "আইটি",
    "Last Modified": "সর্বশেষ পরিবর্তিত",
    Last: "সর্বশেষ",
    Modified: "পরিবর্তিত",
    Today: "আজ",
    "Last Week": "শেষ সপ্তাহ",
    "Last Month": "শেষ মাস",
    "Date Added": "তারিখ যোগ ",
    Date: "তারিখ",
    Added: "যোগ করা হয়েছে",
    "Newest First": "নতুন থেকে শুরু",
    "Oldest First": "পুরাতন থেকে শুরু",
    Search: "অনুসন্ধান",
    Notification: "বিজ্ঞপ্তি",
    Online: "অনলাইন",
    "Set Status": "অবস্থা নির্ধারণ",
    Settings: "সেটিংস",
    "Share Your Opinion": "আপনার মতামত শেয়ার করুন",
    Class: "শ্রেণী",
    English: "ইংরেজী",
    "Add Class": "ক্লাস যোগ করুন",
    Save: "সংরক্ষণ করুন",
    "Add New": "নতুন যোগ করুন",
    Serial: "সিরিয়াল",
    Sections: "সাব ক্লাস",
    Bangla: "বাংলা",
    Arabic: "আরবি",
    User: "ইউজার",
    Filter: "ফিল্টার",
    "Not Admitted students": "ভর্তি না হওয়া শিক্ষার্থী",
    "Admitted students": "ভর্তিকৃত শিক্ষার্থী ",
    "Complete Admission": "ভর্তি সম্পূর্ন করুন",
    "Admitted Students List": "ভর্তিকৃত ছাত্র তালিকা",
    "Not Admitted Students List": "ভর্তি না হওয়া শিক্ষার্থীদের তালিকা",
    "Student Name": "শিক্ষার্থীর নাম",
    "Father Name": "পিতার নাম",
    Mobile: "মোবাইল",
    "Entry Date": "এন্টি তারিখ",
    Session: "শিক্ষাবর্ষ",
    "Admission Class": "ভর্তি ইচ্ছুক ক্লাস",
    "Admission Serial": "ভর্তি সিরিয়াল",
    "Financial Condition": "আর্থিক অবস্থা",
    "Living Condition": "আবাসন অবস্থা",
    "Admission Type": "ভর্তির ধরণ",
    Select: "নির্বাচন করুন",
    "Admission Details": "ভর্তির ফরম",
    "Request already in progress. Please wait...":
      "অনুরোধ ইতিমধ্যে প্রক্রিয়াধীন। অনুগ্রহ করে অপেক্ষা করুন...",
    "Information Added Successfully": "তথ্য যুক্ত করা হয়েছে।",
    Employee: "কর্মচারী",
    "Admitted Teacher List": "যোগদেয়া কর্মীদের তালিকা",
    "Not Admitted Teacher List": "যোগ না দেয়া কর্মীদের তালিকা",
    Account: "একাউটিং",
    "User ID": "উজার আইডি",
    "Teacher Code": "শিক্ষক কোড",
    "Father Name": "বাবার নাম",
    "Date of join": "যোগদানের তারিখ",
    "Inter your date of join": "যোগদানের তারিখ যোগ করুন",
    "Inter your result devision": "ফলাফল বিভাগ যোগ করুন",
    "Inter your passted date": "পাসের তারিখ যোগ করুন",
    "Inter your qualification": "যোগ্যতা যোগ করুন",
    "Inter your exam board name": "পররীক্ষার বোর্ডের নাম যোগ করুন",
    "Inter your experience": "অভিজ্ঞতা যোগ করুন",
    "Employee Details": "কর্মচারী বিবরণ",
    "Enter image": "ছবি প্রবেশ করান",
    "Serial Title": "শিরোনাম সিরিয়াল",
    "Result Devision": "ফলাফল বিভাগ",
    Year: "পাসের বছর",
    "Exam Board Name": "পররীক্ষার বোর্ডের নাম",
    "Teacher Info Update": "শিক্ষক তথ্য আপডেট",
    "Designation List": "পদবী তালিকা",
    "Create Designation": "পদবী তৈরি করুন",
    "Update Designation": "পদবী আপডেট করুন",
    "Enter new designation": "নতুন পদবি লিখুন",
    "Teacher Register": "শিক্ষক নিবন্ধন",
    Account: "একাউটিং",
    Mobile1: "মোবাইল ১",
    Name: "নাম",
    Gender: "লিঙ্গ",
    Action: "অ্যাকশন",
    Register: "রেজিস্টার সম্পুর্ণ করুন",
    Experience: "অভিজ্ঞতা",
    Qualification: "যোগ্যতা",
    Designation: "পদবী",
    "User Code": "ইউজার কোড",
    Varient: "প্রকার",
    Type: "ধরন",
    Remark: "মন্তব্য",
    "Character Report": "চারিত্রিক রিপোর্ট",
    "No.": "ক্র: নং",
    "Total students": "মোট শিক্ষার্থী",
    "Total teachers": "মোট শিক্ষক",
    "Total donor member": "মোট দাতা সদস্য",
    "Total owed": "মোট পাওনা",
    "Class-based student distribution": "শ্রেণি ভিত্তিক শিক্ষার্থী বন্টন",
    Calendar: "ক্যালেন্ডার",
    "Number of students by class": "ক্লাস ভিত্তিক শিক্ষার্থীর সংখ্যা",
    "Presence and absence": "উপস্থিতি ও অনুপস্থিতি",
    "Number of students according to the previous academic year":
      "বিগত শিক্ষাবর্ষ অনুযায়ী শিক্ষার্থী সংখ্যা",
  };

  return (key) =>
    currectLanguage === "bn" ? englishToBangla[key] || key : key;
};

export default useTranslate;
