import { useSelector } from 'react-redux';

const useTranslate = () => {
  const { currectLanguage } = useSelector((state) => state.language);

  const englishToBangla = {
    Home: 'হোম',
    'Home Work': 'হোম ওয়ার্ক',
    Student: 'শিক্ষার্থী',
    'Book List': 'বুক লিস্ট',
    'List of Candidates': 'পরীক্ষার্থীর তালিকা',
    Status: 'স্ট্যাটাস',
    Reset: 'রিসেট',
    Delete: 'ডিলিট',
    Edit: 'এডিট',
    Debit: 'ডেবিট',
    Credit: 'ক্রেডিট',
    SubLedger: 'সাবলেজার',
    'Transaction ID': 'ট্রানজেকশন আইডি',
    'Student Payment History': 'পেমেন্ট তথ্য',
    'Invoice Type': 'ইনভয়েস ধরণ',
    'Maddrasah Name': 'মাদ্রাসার নাম',
    'Select Type': 'ধরণ নির্বাচন করুন',
    'Maddrasah ID': 'মাদ্রাসার আইডি',
    'Store ID': 'স্টোর আইডি',
    'Store Password': 'স্টোর পাসওয়ার্ড',
    'Maddrasah ID': 'মাদ্রাসার আইডি',
    'Prayer Break': 'শুক্রবার ছুটি',
    'User Select': 'ইউজার নির্বাচন করুন',
    'User Notice': 'ইউজার নোটিশ',
    'Notice': 'নোটিশ',
    'Admission Deadline Date': 'ভর্তির সময়সীমা তারিখ',
    'Admission Deadline': 'ভর্তির সময়সীমা',
    'Online Admission Message': 'অনলাইন ভর্তির মেসেজ',
    'Message 1st Part': 'মেসেজ ১ম অংশ',
    'Message 2nd Part': 'মেসেজ ২য় অংশ',
    'Message 3rd Part': 'মেসেজ ৩য় অংশ',
    Time: 'সময়',
    'Time Slots': 'সময়-স্লট',
    'Ledger No': 'লেজার নম্বর',
    'English Date': 'ইংরেজী তারিখ',
    'Solve User Name': 'সমাধানকারী নাম',
    'Solution Description': 'সমাধানের বর্ণনা',
    'Invoice Details': 'ইনভয়েস বিস্তারিত',
    'Total Amount': 'মোট পরিমাণ',
    'Class Work': 'পড়া',
    'Online Payment Invoice': 'অনলাইন পেমেন্ট ইনভয়েস',
    'Payment Type': 'পেমেন্ট ধরণ',
    'Home Work': 'বাড়ির কাজ',
    'Parent Panel': 'অভিভাবক প্যানেল',
    'Maddrasah Payment Info': 'মাদ্রাসা পেমেন্ট তথ্য',
    'Website Settings': 'ওয়েবসাইট সেটিং',
    'Homework Subject History': 'বিষয় ভিত্তিক হোমওয়ার্ক',
    'Homework History': 'হোমওয়ার্ক রিপোর্ট',
    Password: 'পাসওয়ার্ড',
    'Total Day': 'মোট দিন',
    'Admission Status': 'ভর্তি অবস্থা',
    'Single off': 'একক বন্ধ',
    'Month off': 'মাসিক বন্ধ',
    'Total Holiday': 'মোট ছুটির দিন',
    'New Password': 'নতুন পাসওয়ার্ড',
    'Student Performance Chart': 'শিক্ষার্থীদের কর্মক্ষমতা চার্ট',
    'Sub Class Bangla': 'সাব ক্লাস বাংলা',
    'Exam Group Select': 'পরীক্ষার গ্রুপ তৈরি',
    CurrentPaid: 'বর্তমান জমা',
    'Balance Transfer': 'ব্যালেন্স ট্রান্সফার',
    'Database Name': 'ডাটাবেজ নাম',
    'Institution Name': 'প্রতিষ্ঠানের নাম',
    'Last Login': 'শেষ লগইন',
    'Class Video': 'ক্লাস ভিডিও',
    'Class Routine': 'ক্লাস রুটিন',
    'Exam Rules': 'পরীক্ষার নিয়ম',
    'Report/Type': 'রিপোর্ট/ধরণ',
    'Payment System': 'পেমেন্ট সিস্টেম',
    Quantity: 'পরিমাণ',
    'User Roles': 'ব্যবহারকারীর ভূমিকা',
    'Student admission completed.': 'শিক্ষার্থী ভর্তি সম্পূর্ণ হয়েছে।',
    'New User': 'নতুন ব্যবহারকারী',
    'Payment Comments': 'পেমেন্ট মন্তব্য',
    'Voucher/Bill': 'ভাউচার/বিল',
    Voucher: 'ভাউচার',
    'Deposit/Cost': 'জমা/খরচ',
    'All Madrasah List': 'সকল মাদ্রাসা তালিকা',
    'All Madrasah': 'সকল মাদ্রাসা',
    'Fee Collection': 'ফি গ্রহণ করা',
    Collection: 'আদায়',
    'Admit Card View': 'এডমিট কার্ড দেখা',
    'Admit Card Design': 'এডমিট কার্ড ডিজাইন',
    'Student Financial Status': 'শিক্ষার্থীর আর্থিক অবস্থা',
    'Student Residential Status': 'শিক্ষার্থীর আবাসিক অবস্থা',
    'New and Old': 'নতুন ও পুরাতন',
    'Search Id': 'আইডি দিয়ে সার্চ করুন',
    'Card Name': 'কার্ড নাম',
    Card: 'কার্ড',
    'Receipt No': 'রশিদ নং',
    Talimat: 'তালিমাত',
    'Complaint Box Terms and Conditions': 'অভিযোগ বক্স শর্তাবলী',
    'Student Complaints': 'শিক্ষার্থী অভিযোগসমূহ',
    'Acc Rosid Satting': 'হিসাব রসিদ সেটিং',
    'Message Admission': 'ভর্তি মেসেজ',
    'Donor SMS': 'দানকারী এসএমএস',
    'Month Fee SMS': 'মাসিক ফি এসএমএস',
    'Rosid Number Satting': 'রসিদ নাম্বার সেটিং',
    'Rosid Book Satting': 'রসিদ বই সেটিং',
    'Yearly/Monthly': 'বার্ষিক/মাসিক',
    'Permanently Less From Student Monthly Fee':
      'শিক্ষার্থীর মাসিক ফি স্থায়ীভাবে কমানো',
    'Student Admission‍ Serial Setting': 'শিক্ষার্থী ভর্তি সিরিয়াল সেটিং',
    'Average / Point': 'গড় / পয়েন্ট',
    'Quota style of students': 'শিক্ষার্থীদের কোটার ধরন',
    'Teacher Salary To Account': 'শিক্ষকের বেতন হিসাবেতে',
    'Exam Fee Together/Separate': 'পরীক্ষার ফি একত্রে/আলাদা',
    'Add Together Exam fee to Accounting': 'পরীক্ষার ফি একত্রে হিসাবেতে যোগ',
    'Add Monthly fee to Accounting': 'মাসিক ফি হিসাবেতে যোগ',
    'Add Donor fee to Accounting': 'দান ফি হিসাবেতে যোগ',
    'Gate Pass Receipt': 'গেট পাস রসিদ',
    Receipt: 'রসিদ',
    'Receipt Type': 'রসিদের ধরণ',
    'Month ID': 'মাস আইডি',
    'Teach Salary System Setting': 'শিক্ষক বেতন সিস্টেম সেটিং',
    'User gender': 'ব্যবহারকারীর লিঙ্গ',
    'User Information': 'ব্যবহারকারীর তথ্য',
    'Student Fee Collection': 'শিক্ষার্থীর ফি গ্রহণ',
    Description: 'ডেসক্রিপশন',
    Renewal: 'নবায়ন',
    'Class Name': 'ক্লাস নাম',
    'Delete Edit Record': 'ডিলিট এডিট রেকর্ড',
    'Fee Name': 'ফি নাম',
    'Male Residence': 'ছাত্র আবাসিক',
    Residence: 'আবাসিক',
    'Female Residence': 'ছাত্রী আবাসিক',
    'Login Name': 'লগইন নাম',
    'Login Type': 'লগইন ধরণ',
    'Renewal Date': 'নবায়ন তারিখ',
    'Renewal end': 'নবায়ন শেষ',
    'Print View': 'প্রিন্ট ভিউ',
    'Subject Pass Number': 'বিষয় পাস নম্বর',
    'Average Determination': 'গড় নির্ণয়',
    'SMS ID': 'এসএমএস আইডি',
    'Report Type': 'রিপোর্টের ধরণ',
    'Phone Number': 'ফোন নম্বর',
    'Success and Error': 'সাকসেস এবং এরোর',
    'Book of Subjects': 'বিষয়ের খাতা',
    'Application No': 'আবেদন নাম্বার',
    'Subject and Pass Number': 'বিষয় এবং পাস নম্বর',
    'Results Condition': 'ফলাফল কন্ডিশন',
    'Pass Number': 'পাস নাম্বার',
    'Point Condition Status': 'পয়েন্ট কন্ডিশন স্ট্যাটাস',
    'Then Division': 'তাহলে ডিভিশন',
    'Silver Color': 'সিলভার কালার',
    'User Name': 'ইউজার নাম',
    'Result Report': 'ফলাফল রিপোর্ট',
    'Size Status': 'সাইজ স্ট্যাটাস',
    'Double Student D:': 'ডাবল শিক্ষার্থী ডি:',
    'Online Result Public': 'অনলাইন ফলাফল প্রকাশ',
    Optional: 'অপশনাল',
    'Christian Date': 'ঈসায়ী তারিখ',
    'Arabic Date': 'আরবী তারিখ',
    'Monthly Dues': 'মাসিক বকেয়া',
    'Dues List': 'বকেয়া তালিকা',
    'Dues Types': 'বকেয়ার ধরণ',
    'Deposit Costs': 'জমা খরচ',
    'Test condition type': 'পরীক্ষার কন্ডিমন ধরন',
    'Admission fee, monthly fee and exam fee will be added to the accounting':
      'ভর্তি ফি, মাসিক ফি এবং পরীক্ষা ফি একাউন্টিং এ যুক্ত হবে',
    'Donations will be added to the accounting':
      'দান অনুদানের টাকা একাউন্টিং এ যুক্ত হবে।',
    'Teacher/staff salary will be deducted from the main accounting':
      'শিক্ষক/স্টাফ বেতন মূল একাউন্টিং থেকে কর্তন হবে।',
    'Collection of student examination fees': 'শিক্ষার্থীর পরীক্ষার ফি গ্রহন।',
    "The student's exam fee will be added to the accounting":
      'শিক্ষার্থীর একত্রে পরীক্ষার ফি একাউন্টিং এ যুক্ত হবে।',
    'Average based': 'গড় ভিত্তিক',
    'Point based': 'পয়েন্ট ভিত্তিক',
    Yes: 'হাঁ',
    No: 'না',
    Together: 'একত্রে',
    Separate: 'আলাদা',
    Creditor: 'পাওনাদার',
    Due: 'পাওনা',
    'Donor Name': 'দাতার নাম',
    Donor: 'দাতা',
    Father: 'বাবা',
    Sectors: 'খাত সমূহ',
    Start: 'শুরু',
    'Next Date': 'পরবর্তী তারিখ',
    End: 'শেষ',
    'Cofil 1': 'কফিল ১',
    'Cofil 2': 'কফিল ২',
    'Cofil 3': 'কফিল ৩',
    'Donor Fee Determination': 'দাতার ফি নির্ধারন',
    Total: 'মোট',
    'Total Deposits': 'মোট জমা',
    Deposit: 'জমা',
    'Grand Total': 'সর্বমোট',
    'Previous Balance': 'পূর্ব পাওনা',
    'Pre-deposit': 'পূর্ব জমা',
    'All paid': 'সর্ব প্রদেয়',
    'Total Payable': 'মোট প্রদেয়',
    'Total Fee': 'মোট ফি',
    'East cut': 'পূর্ব কর্তন',
    'Current deposit': 'বর্তমান জমা',
    Received: 'গ্রহণ/আদায়',
    Due: 'বকেয়া',
    Recipient: 'গ্রহীতা',
    'Delete Edit Data and Time': 'ডিলিট এডিট তারিখ ও সময়',
    'Deleted/Edited By': 'ডিলিট এডিট কারী',
    'In Words': 'কথায়',
    'Account Type': 'অ্যাকাউন্টের ধরণ',
    'Data Type': 'ডাটার ধরণ',
    'Add New Donation': 'অনুদান তৈরি করুন',
    'Dues list and dues messages of all students':
      'সকল শিক্ষার্থীর বকেয়া তালিকা ও বকেয়া মেসেজ',
    Debtor: 'দেনাদার',
    'With ID': 'আইডি দিয়ে',
    'With Name': 'নাম দিয়ে',
    'Search Type': 'সার্চের ধরণ',
    'Fee Collection Report': 'ফি গ্রহনের রিপোর্ট',
    'Point V: Condition': 'পয়েন্ট ভি: কন্ডিশন',
    Staff: 'স্টাফ',
    SubClass: 'সাব ক্লাস',
    'Point Based Mark Sheet': 'পয়েন্ট ভিত্তিক মার্ক শীট',
    'A4 Mark Sheet': 'A4 মার্কশীট',
    'A5 Mark Sheet': 'A5 মার্কশীট',
    'Exam Name': 'পরীক্ষার নাম',
    'Exam Routing Create': 'পরীক্ষার রুটিন তৈরি',
    'Fee Name': 'ফি-এর নাম',
    'Sub Ledger (Fee Name)': 'সাব লেজার (ফি-এর নাম)',
    'Exam Report': 'পরীক্ষার রিপোর্ট',
    'Result Type': 'ফলাফলের ধরণ',
    'Point V: Report': 'পয়েন্ট ভি: রিপোর্ট',
    'Fee Setting': 'ফি সেটিংস',
    'Accepted Fees': 'গৃহীত ফি',
    Fee: 'ফি',
    Fund: 'ফান্ড',
    Langauge: 'ভাষা',
    'Exam Routine': 'পরীক্ষার রুটিন',
    'Color Status': 'রঙের অবস্থা',
    'Point Result Entry': 'পয়েন্ট ফলাফল এন্ট্রি',
    'Hall No': 'হল নং',
    'Hall Name': 'হল নাম',
    'Student Admission': 'ছাত্র ভর্তি',
    'Personal Information': 'ব্যক্তিগত তথ্য',
    'Permanent Address Information': 'স্থায়ী ঠিকানা তথ্য',
    'Present Address Information': 'বর্তমান ঠিকানা তথ্য',
    'Educational Information': 'শিক্ষাগত তথ্য',
    'Average based Condition': 'গড় ভিত্তিক অবস্থা',
    'Highest recitation score': 'তেলাওয়াতের সর্বোচ্চ নম্বর',
    'Highest score': 'সর্বোচ্চ নম্বর',
    'Average Condition': 'গড় নম্বর',
    'Data Not Found': 'ডটা পাওয়া যায়নি',
    'Score value': 'স্কোর মান',
    'If >=': 'যদি >=',
    'Or If >=': 'অথবা যদি >=',
    'Fee Type': 'ফি ধরণ',
    'Prescribed Fee': 'নির্ধারিত ফি',
    'Total Subject': 'মোট বিষয়',
    Subject: 'বিষয়',
    Prescribed: 'বিষয়',
    'Select those to whom you will charge fees.':
      'যাদের কাছ থেকে আপনি ফি নেবেন তাদের নির্বাচন করুন।',
    'Accept the following student fees.':
      'নিম্নোক্ত শিক্ষার্থীদের ফ্রী গ্রহণ করুন।',
    'Talent Condition': 'মেধা কন্ডিশন',
    'All the divisions whose merit will be mentioned':
      'যে সকল ডিভিশনের মেধা উল্লেখ করা হবে।',
    'Select it with a check mark.': 'তা টিক চিহ্ন দিয়ে নির্বাচন করুন।',
    'Select all inputs': 'সকল ইনপুট নির্বাচন করুন।',
    'Exam List Made': 'পরীক্ষার তালিকা তৈরি',
    'Average V: Condition': 'গড় ভি: কন্ডিশন',
    'Average V: Report': 'গড় ভি: রিপোর্ট',
    'Online F: Publish': 'অনলাইন ফ: প্রকাশ',
    'General Ledger': 'জেনারেল লেজার',
    'Sub Ledger (Fee Name)': 'সাব লেজার (ফি এর নাম)',
    'Sub Ledger': 'সাব লেজার',
    'G Ledger': 'জি: লেজার',
    'Student Fee Group': 'ছাত্র ফি গ্রুপ',
    'Chart account': 'চার্ট একাউন্ট',
    'Exam Fee Determine': 'পরীক্ষার ফি নির্ধারণ ',
    'Book of subjects': 'বিষয়ের খাতা',
    'Class And Subclass': 'ক্লাস এবং সাব ক্লাস',
    'Please select filters to view exam conditions':
      'পরীক্ষার শর্তাবলী দেখতে ফিল্টার নির্বাচন করুন।',
    'Select columns to display data':
      'ডেটা প্রদর্শনের জন্য কলাম নির্বাচন করুন।',
    'No data available for the selected filters':
      'নির্বাচিত ফিল্টারগুলির জন্য কোনও ডেটা উপলব্ধ নেই।',
    Sequential: 'ক্রমিক',
    "Average Mi'iary any": 'গড় মি‘ইয়ারি যে কোনো',
    "Mi'iary any": 'মি‘ইয়ারি যে কোনো',
    "Average Mi'iary": 'গড় মি‘ইয়ারি',
    "Mi'iary": 'মি‘ইয়ারি',
    "Higher Mi'iary": 'অধিকতর মি‘ইয়ারি',
    'Condition-1 : Regarding the failure of the average math book':
      'কন্ডিশন-1 : গড় মি”ইয়ারী কিতাবের ফেল সংক্রান্ত',
    "Condition-2 : Regarding the failure of the Mi'Yari book":
      'কন্ডিশন-2 : মি”ইয়ারী কিতাবের ফেল সংক্রান্ত',
    "Condition-3 : More about the failure of the Mi'yari book":
      'কন্ডিশন-3 : অধিকতর মি”ইয়ারী কিতাবের ফেল সংক্রান্ত',
    'Condition-4 : Optional Subject': 'কন্ডিশন-4 : অপশনাল বিষয়',
    'Condition-5 : (If a number is not entered for a subject)':
      'কন্ডিশন-5 : (যদি কোন এক বিষয়ে নাম্বার এন্ট্রি না হয়)',
    Optional: 'অপশনাল',
    Schedule: 'সময়সূচী',
    'Subject ID': 'সাবজেক্ট আইডি',
    'If someone fails in this way or less, then':
      'কিভাবে অথবা এর চেয়ে কম ফেল করে তাহল',
    'Fails in the subject, then': 'বিষয়ে ফেল করে তাহল',
    'If someone fails more than that': 'এর চেয়ে বেশি ফেল করলে',
    'If someone fails in': 'যে কোন',
    subjects: 'টি বিষয়ে ফেল করলে',
    'If the grade in the optional subject is above how much, will it be added to the main grade':
      'অপশনাল বিষয়ের গ্রেড কত এর বেশি হলে মূল গ্রেডের সাথে যোগ হবে',
    'If there are entries or numbers left in any subject, then division will be done.':
      'যদি কোন এক বিষয়ে এন্ট্রি বা নাম্বার বাকি থাকে তাহলে ডিভিশন হবে',
    'Subject Name': 'সাবজেক্ট নাম',
    'Please specify the number of merit points.':
      'মেধার সংখ্যা কত ভাগে তা উল্লেখ করুন',
    'English Name': 'ইংরেজী নাম',
    'Arabic Name': 'আরবী নাম',
    'Class Group': 'ক্লাস গ্রুপ',
    'Created At': 'তৈরি করার তারিখ',
    'Updated At': 'আপডেট করার তারিখ',
    'Application No': 'আবেদন নাম্বার',
    Gender: 'লিঙ্গ',
    'Date of Birth': 'জন্ম তারিখ',
    Village: 'গ্রাম',
    'Post Office': 'ডাকঘর',
    Division: 'বিভাগ',
    'Police Station': 'থানা',
    Exam: 'পরীক্ষা',
    Libery: 'লাইব্রেরি',
    Residence: 'আবাসিক',
    'Payment History': 'পেমেন্টের তালিকা',
    'Group distribution': 'গ্রুপ বন্টন',
    'Change group': 'গ্রুপ পরিবর্তন',
    'Group Distribution List': 'গ্রুপ বিতরণ তালিকা',
    'Group Change History': 'গ্রুপ পরিবর্তনের ইতিহাস',
    'NID/Birth Registration': 'জাতীয় পরিচয়পত্র/জন্ম নিবন্ধন',
    'NID Number': 'জাতীয় পরিচয়পত্র নম্বর',
    Others: 'অন্যান্য',
    'Blood Group': 'রক্তের গ্রুপ',
    'Financial Status': 'আর্থিক অবস্থা',
    SMS: 'এসএমএস',
    Balance: 'ব্যালেন্স',
    Book: 'কিতাব',
    'Create Certificate of Attestation': 'প্রত্যয়ন পত্র তৈরি করুন',
    Section: 'সাব ক্লাস',
    'Certificate of Attestation List': 'প্রত্যয়ন পত্রর তালিকা',
    'Create Certificate': 'পত্র তৈরি করুন',
    'Update Certificate of Attestation': 'প্রত্যয়ন পত্র আপডেট করুন',
    'All Students': 'সকল শিক্ষার্থী',
    'Students Report': 'শিক্ষার্থী রিপোর্ট',
    'Student Vacation': 'শিক্ষার্থী ছুটি',
    'Group Distribution': 'শিক্ষার্থী গ্রুপ সেটিং',
    'Certificate of Attestation': 'প্রত্যয়ন পত্র',
    'Online Admission': 'অনলাইন ভর্তি',
    'Sub Class': 'সাব ক্লাস',
    'Online Admission List': 'অনলাইন ভর্তি তালিকা',
    'New/Old': 'নতুন/পুরাতন',
    New: 'নতুন',
    Old: 'পুরাতন',
    'Male Non-resident': 'ছাত্র অনাবাসিক',
    'Non-resident': 'অনাবাসিক',
    'Male Student': 'ছাত্র',
    'Female Student': 'ছাত্রী',
    'Female Non-resident': 'ছাত্রী অনাবাসিক',
    'Male Daycare': 'ছাত্র ডে-কেয়ার',
    Daycare: 'ডে-কেয়ার',
    'Enter TK': 'টাকা লিখুন',
    'Check All': 'সব চেক করুন',
    'Female Daycare': 'ছাত্রী ডে-কেয়ার',
    'Excel File Name': 'এক্সেল ফাইলের নাম',
    'Export students data': 'শিক্ষার্থীদের তথ্য সেভ করুন',
    'Data Export': 'ডাটা এক্সপোর্ট',
    'Send single and multiple SMS': 'একক এবং একাধিক এসএমএস পাঠান',
    'SMS Sending Form': 'মেসেজ প্রেরণ ফর্ম',
    'Missing or invalid data provided': 'কোন তথ্য পাওয়া যায়নি',
    'Buy SMS': 'মেসেজ কিনুন',
    '1st Month': '১ম মাস',
    '2nd Month': '২য় মাস',
    '3rd Month': '৩য় মাস',
    '4th Month': '৪র্থ মাস',
    '5th Month': '৫ম মাস',
    '6th Month': '৬ষ্ঠ মাস',
    '7th Month': '৭ম মাস',
    '8th Month': '৮ম মাস',
    '9th Month': '৯ম মাস',
    '10th Month': '১০ম মাস',
    '11th Month': '১১তম মাস',
    '12th Month': '১২তম মাস',
    'Enter name or number for 1st Month': '১ম মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 2nd Month': '২য় মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 3rd Month': '৩য় মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 4th Month': '৪র্থ মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 5th Month': '৫ম মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 6th Month': '৬ষ্ঠ মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 7th Month': '৭ম মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 8th Month': '৮ম মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 9th Month': '৯ম মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 10th Month': '১০ম মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 11th Month': '১১তম মাসের নাম্বার বা নাম লিখুন',
    'Enter name or number for 12th Month': '১২তম মাসের নাম্বার বা নাম লিখুন',
    'Months list table': 'মাসের তালিকা টেবিল',
    'Months create': 'মাস তৈরি',
    'Session is required': 'সেশন প্রয়োজন',
    'Class is required': 'ক্লাস প্রয়োজন',
    '1st Month name is required': '১ম মাস প্রয়োজন',
    '2nd Month name is required': '২য় মাস প্রয়োজন',
    '3rd Month name is required': '৩য় মাস প্রয়োজন',
    '4th Month name is required': '৪র্থ মাস প্রয়োজন',
    '5th Month name is required': '৫ম মাস প্রয়োজন',
    '6th Month name is required': '৬ষ্ঠ মাস প্রয়োজন',
    '7th Month name is required': '৭ম মাস প্রয়োজন',
    '8th Month name is required': '৮ম মাস প্রয়োজন',
    '9th Month name is required': '৯ম মাস প্রয়োজন',
    '10th Month name is required': '১০ম মাস প্রয়োজন',
    '11th Month name is required': '১১তম মাস প্রয়োজন',
    '12th Month name is required': '১২তম মাস প্রয়োজন',
    Setting: 'সেটিংস',
    'Sahara IT': 'সাহারা আইটি',
    'List of Applicants': 'আবেদনকারীদের তালিকা',
    Sahara: 'সাহারা',
    IT: 'আইটি',
    'Last Modified': 'সর্বশেষ পরিবর্তিত',
    Last: 'সর্বশেষ',
    Modified: 'পরিবর্তিত',
    'Update Student Report': 'ছাত্র রিপোর্ট আপডেট',
    Today: 'আজ',
    Day: 'দিন',
    Month: 'মাস',
    'Last Week': 'শেষ সপ্তাহ',
    'Last Month': 'শেষ মাস',
    'Date Added': 'তারিখ যোগ',
    'User Based Report': 'ব্যবহারকারী ভিত্তিক প্রতিবেদন',
    Report: 'রিপোর্ট',
    Preview: 'প্রিভিউ',
    'General Information': 'সাধারণ তথ্য',
    'User Reports': 'ব্যবহারকারী রিপোর্ট',
    'User Types': 'ব্যবহারকারীর ধরন',
    Date: 'তারিখ',
    Added: 'যোগ করা হয়েছে',
    'Newest First': 'নতুন থেকে শুরু',
    'Oldest First': 'পুরাতন থেকে শুরু',
    'Create Type': 'ছুটির ধরন তৈরি করুন',
    'From Time': 'সময় থেকে',
    From: 'হতে',
    To: 'পযর্ন্ত',
    'Be Time': 'সময় হতে',
    Search: 'অনুসন্ধান',
    'Mother Name': 'মাতার নাম',
    Years: 'সাল',
    'User Status': 'ব্যবহারকারীর অবস্থা',
    'User Search': 'ইউজার সার্চ',
    'User Type': 'ব্যবহারকারীর ধরণ',
    'New User Code': 'দাখেলা',
    Active: 'অ্যাক্টিভ',
    InActive: 'ইনঅ্যাক্টিভ',
    Both: 'উভয়',
    Notification: 'বিজ্ঞপ্তি',
    'Start Year': 'সাল হতে',
    'End Year': 'সাল পর্যন্ত',
    Online: 'অনলাইন',
    'Set Status': 'অবস্থা নির্ধারণ',
    Settings: 'সেটিংস',
    'Share Your Opinion': 'আপনার মতামত শেয়ার করুন',
    Class: 'ক্লাস',
    Branch: 'শাখা',
    'Class/Jamaat': 'শ্রেণী/জামাত',
    English: 'ইংরেজী',
    'Add Class': 'ক্লাস যোগ করুন',
    Save: 'সংরক্ষণ করুন',
    'Certification update': 'প্রত্যায়ন আপডেট করুন',
    'Add New': 'নতুন যোগ করুন',
    Serial: 'সিরিয়াল',
    Sections: 'সাব ক্লাস',
    Bangla: 'বাংলা',
    Arabic: 'আরবি',
    'Will.': 'হবে।',
    'Create month names': 'মাসের নাম তৈরি করুন',
    'Update month names': 'মাসের নাম আপডেট করুন',
    User: 'ইউজার',
    Filter: 'ফিল্টার',
    'Not Admitted students': 'ভর্তি না হওয়া শিক্ষার্থী',
    'Students Admission': 'শিক্ষার্থী ভর্তি',
    'Admitted students': 'ভর্তিকৃত শিক্ষার্থী ',
    'Complete Admission': 'ভর্তি সম্পূর্ন করুন',
    'Admitted Students List': 'ভর্তিকৃত ছাত্র তালিকা',
    'Not Admitted Students List': 'ভর্তি না হওয়া শিক্ষার্থীদের তালিকা',
    'Student Name': 'শিক্ষার্থীর নাম',
    'Father Name': 'পিতার নাম',
    Mobile: 'মোবাইল',
    'Entry Date': 'এন্টি তারিখ',
    'Students List': 'শিক্ষার্থীর তালিকা',
    'Admit Card': 'প্রবেশপত্র',
    Session: 'শিক্ষাবর্ষ',
    Vacation: 'ছুটি',
    Single: 'একক',
    'Class Based': 'ক্লাস ভিত্তিক',
    Vacation: 'ছুটি',
    'Admission Class': 'ভর্তি ইচ্ছুক ক্লাস',
    'Admission Serial': 'ভর্তি সিরিয়াল',
    'Financial Condition': 'আর্থিক অবস্থা',
    'Living Condition': 'আবাসন অবস্থা',
    'Admission Type': 'ভর্তির ধরণ',
    Select: 'নির্বাচন করুন',
    'Admission Details': 'ভর্তির ফরম',
    'Request already in progress. Please wait...':
      'অনুরোধ ইতিমধ্যে প্রক্রিয়াধীন। অনুগ্রহ করে অপেক্ষা করুন...',
    'Information Added Successfully': 'তথ্য যুক্ত করা হয়েছে।',
    Employee: 'কর্মচারী',
    'Admitted Teacher List': 'যোগদেয়া কর্মীদের তালিকা',
    'Not Admitted Teacher List': 'যোগ না দেয়া কর্মীদের তালিকা',
    Account: 'অ্যাকাউন্ট',
    'User ID': 'ইউজার আইডি',
    'Book Name': 'কিতাবের নাম',
    'Add Book': 'কিতাব যোগ করুন',
    'Update Book': 'কিতাব আপডেট করুন',
    "Student's English Name": 'শিক্ষার্থীর ইংরেজি নাম',
    'Start User ID': 'ইউজার আইডি হতে',
    'End User ID': 'ইউজার আইডি পর্যন্ত',
    'Enter start user id': 'ব্যবহারকারী আইডি হতে লিখুন',
    'Enter end user id': 'ব্যবহারকারী আইডি পর্যন্ত লিখুন',
    'Teacher Code': 'শিক্ষক কোড',
    'Father Name': 'বাবার নাম',
    GPA: 'জিপিএ',
    'Published Status': 'প্রকাশিত স্ট্যাটাস',
    'Date of join': 'যোগদানের তারিখ',
    'Inter your date of join': 'যোগদানের তারিখ যোগ করুন',
    'Inter your result devision': 'ফলাফল বিভাগ যোগ করুন',
    'Inter your passted date': 'পাসের তারিখ যোগ করুন',
    'Inter your qualification': 'যোগ্যতা যোগ করুন',
    'Inter your exam board name': 'পররীক্ষার বোর্ডের নাম যোগ করুন',
    'Inter your experience': 'অভিজ্ঞতা যোগ করুন',
    'Employee Details': 'কর্মচারী বিবরণ',
    Details: 'বিবরণ',
    'Enter image': 'ছবি প্রবেশ করান',
    'User Image': 'ব্যবহারকারী ছবি',
    'Bulk Image': 'বাল্ক ছবি',
    'Upload Profile Images': 'প্রোফাইল ছবি আপলোড',
    'Upload multiple user profile images at once. File names must match UserCode (numeric only).':
      'একসাথে একাধিক ব্যবহারকারীর প্রোফাইল ছবি আপলোড করুন। ফাইলের নাম অবশ্যই UserCode এর সাথে মিলতে হবে (শুধুমাত্র সংখ্যাসূচক)।',
    Image: 'ছবি',
    'Upload Profile Image': 'প্রোফাইল ছবি আপলোড',
    'Serial Title': 'শিরোনাম সিরিয়াল',
    'Result Devision': 'ফলাফল বিভাগ',
    Year: 'পাসের বছর',
    Division: 'বিভাগ',
    'Exam Board Name': 'পররীক্ষার বোর্ডের নাম',
    'Teacher Info Update': 'শিক্ষক তথ্য আপডেট',
    'Designation List': 'পদবী তালিকা',
    'Create Designation': 'পদবী তৈরি করুন',
    'Update Designation': 'পদবী আপডেট করুন',
    'Enter new designation': 'নতুন পদবি লিখুন',
    'Teacher Register': 'শিক্ষক নিবন্ধন',
    'From Date': 'তারিখ থেকে ',
    'Up to date': 'তারিখ পর্যন্ত',
    Mobile1: 'মোবাইল ১',
    Name: 'নাম',
    Gender: 'লিঙ্গ',
    Action: 'অ্যাকশন',
    Register: 'রেজিস্টার সম্পুর্ণ করুন',
    Experience: 'অভিজ্ঞতা',
    Qualification: 'যোগ্যতা',
    Designation: 'পদবী',
    Comment: 'মন্তব্য',
    UserHolidayNo: 'ছুটির নাম্বার',
    'Select Columns': 'কলাম নির্বাচন করুন',
    ID: 'নাম্বার',
    Teacher: 'শিক্ষক',
    'Class Work': 'ক্লাস ওয়ার্ক',
    'Create homework': 'হোমওয়ার্ক তৈরি করুন',
    'Update homework': 'হোমওয়ার্ক আপডেট করুন',
    Code: 'কোড',
    'E-mail': 'ই-মেইল',
    'Mobile 1': 'মোবাইল এক',
    'Mobile 2': 'মোবাইল দুই',
    'User Code': 'ইউজার কোড',
    'Student Code': 'শিক্ষার্থীর কোড',
    'Date of entry': 'এন্ট্রি তারিখ',
    'Type of vacation': 'ছুটির ধরণ',
    'Date of leave': 'ছুটির তারিখ',
    'Holiday time': 'ছুটির সময়',
    'Start Date of leave': 'ছুটির তারিখ হতে',
    'End Date of leave': 'ছুটির তারিখ পর্যন্ত',
    'Start Time of leave': 'ছুটির সময় হতে',
    'End Time of leave': 'ছুটির সময় পর্যন্ত',
    'Start Time': 'সময় হতে',
    'End Time': 'সময় পর্যন্ত',
    'Select Time': 'সময় নির্বাচন করুন',
    'Student ID': 'শিক্ষার্থীর আইডি',
    'Marhala/Class': 'মারহালা/ক্লাস',
    'English & Arobi Name': 'ইংরেজি এবং আরবি নাম',
    'List of holidays': 'ছুটির তালিকা',
    'Vacation type list': 'ছুটির তালিকার ধরণ',
    'Type of holiday create': 'তৈরি ছুটির ধরণ',
    'Type of holiday update': 'আপডেট ছুটির ধরণ',
    'Enter type of vacation': 'ছুটির ধরণ লিখুন',
    'Update Student Vacation Info': 'শিক্ষার্থীদের ছুটির তথ্য আপডেট করুন',
    'Create Student Vacation Info': 'শিক্ষার্থীদের ছুটির তথ্য তৈরি করুন',
    'Edit Vacation': 'ছুটি আপডেট করুন',
    'Create Vacation': 'ছুটি তৈরি করুন',
    'Vacation type': 'ছুটির ধরণ',
    Jamaat: 'জামা’য়াত',
    Jamaat: 'জামা’য়াত',
    'Relationship 1': 'সম্পর্ক ১',
    'Relationship 2': 'সম্পর্ক ২',
    Update: 'আপডেট করুন',
    'Total Mark': 'মোট নম্বর',
    Varient: 'প্রকার',
    Type: 'ধরন',
    Remark: 'মন্তব্য',
    Back: 'পিছনে যান',
    'Create new certificate': 'নতুন প্রত্যায়ন তৈরি করুন',
    'Institution Name (Bangla)': 'প্রতিষ্ঠানের নাম (বাংলা)',
    'Institution Name (Arabic)': 'প্রতিষ্ঠানের নাম (আরবি)',
    'Institution Name (English)': 'প্রতিষ্ঠানের নাম (ইংরেজি)',
    'Enter Institution Name (Bangla)': 'প্রতিষ্ঠানের নাম লিখুন',
    'Enter Institution Name (Arabic)': 'প্রতিষ্ঠানের আরবি নাম লিখুন',
    'Enter Institution Name (English)': 'প্রতিষ্ঠানের ইংরেজি নাম লিখুন',
    'Address (Bengali)': 'ঠিকানা (বাংলা)',
    'Address (Arabic)': 'ঠিকানা (আরবি)',
    'Address (English)': 'ঠিকানা (ইংরেজি)',
    'Enter Address (Bengali)': 'আরবি ঠিকানা লিখুন',
    'Enter Address (Arabic)': 'আরবি ঠিকানা লিখুন',
    'Enter Address (English)': 'ইংরেজি ঠিকানা লিখুন',
    Village: 'গ্রাম',
    'Post Office': 'ডাকঘর',
    'Police Station': 'থানা',
    District: 'জেলা',
    'Arabic Village': 'গ্রাম (আরবি)',
    'Arabic Post Office': 'ডাকঘর (আরবি)',
    'Arabic Police Station': 'থানা (আরবি)',
    'Arabic District': 'জেলা (আরবি)',
    'Enter Village': 'গ্রামের নাম লিখুন',
    'Enter Post Office': 'ডাকঘরের নাম লিখুন',
    'Enter Police Station': 'থানার নাম লিখুন',
    'Enter District': 'জেলার নাম লিখুন',
    'Enter Arabic Village': 'গ্রামের আরবি নাম লিখুন',
    'Enter Arabic Post Office': 'ডাকঘরের আরবি নাম লিখুন',
    'Enter Arabic Police Station': 'থানার আরবি নাম লিখুন',
    'Enter Arabic District': 'জেলার আরবি নাম লিখুন',
    'Contact Number': 'ফোন নম্বর',
    'Arabic Contact Number': 'ফোন নম্বর (আরবি)',
    'SMS Mobile': 'এসএমএস মোবাইল',
    'Email Address': 'ইমেইল ঠিকানা',
    'Enter Contact Number': 'ফোন নম্বর লিখুন',
    'Enter Arabic Contact Number': 'আরবি ফোন নম্বর লিখুন',
    'Enter SMS Mobile Number': 'এসএমএস মোবাইল নম্বর লিখুন',
    'Enter Email Address': 'ইমেইল ঠিকানা লিখুন',
    'Institution Code': 'প্রতিষ্ঠান কোড',
    Elhaq: 'ইলহাক',
    'Enter Institution Code': 'প্রতিষ্ঠান কোড লিখুন',
    'Enter Elhaq': 'ইলহাক লিখুন',
    'Principal Name': 'প্রিন্সিপালের নাম',
    'Najem Name': 'নাজেমের নাম',
    'Accountant Name': 'হিসাবরক্ষকের নাম',
    'Enter Principal Name': 'প্রিন্সিপালের নাম লিখুন',
    'Enter Najem Name': 'নাজেমের নাম লিখুন',
    'Enter Accountant Name': 'হিসাবরক্ষকের নাম লিখুন',
    'Institution Names': 'প্রতিষ্ঠানের নামসমূহ',
    Addresses: 'ঠিকানাসমূহ',
    Address: 'ঠিকানা',
    Residential: 'অবস্থান',
    'Admission Status': 'ভর্তি অবস্থা',
    'Location Information': 'অবস্থান সম্পর্কিত তথ্য',
    'Contact Information': 'যোগাযোগের তথ্য',
    'Institution Details': 'প্রতিষ্ঠানের বিস্তারিত',
    'Institution Logo Upload': 'প্রতিষ্ঠানের লোগো আপলোড',
    Signatories: 'দায়িত্বপ্রাপ্ত ব্যক্তিবর্গ',
    Logo: 'ছবি',
    'Institution Name is required': 'প্রতিষ্ঠানের নাম আবশ্যক',
    'Exam Board Name is require': 'পরীক্ষা বোর্ডের নাম আবশ্যক',
    'Result devision is require': 'ফলাফল বিভাগ আবশ্যক',
    'Character Report': 'চারিত্রিক রিপোর্ট',
    'Gate pass and leave': 'গেইট পাশ ও ছুটি',
    'No.': 'ক্র: নং',
    'Total students': 'মোট শিক্ষার্থী',
    'Total teachers': 'মোট শিক্ষক',
    'Total Donor Member': 'মোট দাতা সদস্য',
    'Total owed': 'মোট পাওনা',
    'Class-based student distribution': 'শ্রেণি ভিত্তিক শিক্ষার্থী বন্টন',
    Calendar: 'ক্যালেন্ডার',
    Cancel: 'বাতিল করুন',
    Payment: 'পেমেন্ট',
    'Pay Now': 'পেমেন্ট করুন',
    'Number of students by class': 'ক্লাস ভিত্তিক শিক্ষার্থীর সংখ্যা',
    'Presence and absence': 'উপস্থিতি ও অনুপস্থিতি',
    'Number of students according to the previous academic year':
      'বিগত শিক্ষাবর্ষ অনুযায়ী শিক্ষার্থী সংখ্যা',
    Dashboard: 'ড্যাশবোর্ড',
    'Teacher Staff': 'শিক্ষক কর্মচারী',
    Result: 'ফলাফল',
    'Board Exam': 'বোর্ড পরীক্ষা',
    'Darul Ikama': 'দারুল ইকামা',
    Accounting: 'অ্যাকাউন্টিং',
    Donation: 'দান অনুদান',
    'Donor Report': 'দাতার রিপোর্ট',
    Library: 'পাঠাগার',
    Others: 'অন্যান্য',
    Help: 'সাহায্য',
    'Month Name': 'মাসের নাম',
    'Institution Information': 'প্রতিষ্ঠানের তথ্য',
    Parents: 'অভিভাবক',
    'All Users': 'সকল ইউজার',
    'Mobile Number': 'মোবাইল নম্বর',
    'Message Type': 'মেসেজের ধরন',
    'Enter mobile number': 'মোবাইল নম্বর লিখুন',
    'Message Template': 'মেসেজ টেমপ্লেট',
    Message: 'মেসেজ',
    Deduction: 'কর্তন',
    'Mobile No 1': 'মোবাইল নম্বর ১',
    'Mobile No 2': 'মোবাইল নম্বর ২',
    'Enter your message': 'আপনার মেসেজ লিখুন',
    765: '৭৬৫',
    'Characters typed': 'অক্ষর টাইপ করা হয়েছে',
    'next SMS from 67 chars': '৬৭টি অক্ষর থেকে পরবর্তী এসএমএস',
    '1 SMS': '১ মেসেজ',
    '70 Char/SMS': '৭০ অক্ষর/মেসেজ',
    'Send SMS': 'মেসেজ পাঠান',
    'Reset SMS': 'মেসেজ রিসেট',
    'To create a list of mobile numbers by typing':
      'টাইপ করে মোবাইল নাম্বারের তালিকা তৈরি করতে',
    'SMS purchase form': 'এসএমএস ক্রয়ের ফর্ম',
    'Please enter the amount of SMS you would like to receive below.':
      'যত টাকার এসএমএস নিতে চান, তত টাকা নিচে উল্লেখ করুন',
    'Amount of Taka': 'টাকার পরিমাণ',
    Amount: 'টাকার পরিমাণ',
    'The amount of money must be paid.': 'টাকার পরিমাণ অবশ্যই দিতে হবে',
    'Enter the amount of money (eg: 500).': 'টাকার পরিমাণ লিখুন (যেমন: ৫০০)',
    'SMS can be purchased from a minimum of 500 Taka.':
      'সর্বনিম্ন ৫০০ টাকা থেকে এসএমএস ক্রয় করা যাবে',
    'SMS Rate: 0.38 Taka per SMS Approximately 1316 SMS can be sent for 500 Taka':
      'এসএমএস এর দর: প্রতি এসএমএস ০.৩৮ টাকা ৫০০ টাকায় প্রায় ১৩১৬ টি এসএমএস পাঠানো যাবে',
    'Message Name': 'মেসেজ নাম',
    'Enter new message name': 'নতুন মেসেজ নাম লিখুন',
    'Invalid Bangladeshi mobile prefix': 'অবৈধ বাংলাদেশী মোবাইল প্রিফিক্স',
    'Mobile number must be 11 digits': 'মোবাইল নম্বর অবশ্যই ১১ সংখ্যার হতে হবে',
    'SMS Templates': 'মেসেজ টেমপ্লেট',
    'SMS Buy': 'মেসেজ কিনুন',
    'This number already exists': 'এই নম্বরটি ইতিমধ্যেই বিদ্যমান।',
    'Write only in Bengali.': 'শুধুমাত্র বাংলা ভাষায় লিখুন।',
    'Write only in English.': 'শুধুমাত্র ইংরেজি ভাষায় লিখুন।',
    'Kerat Condition Type': 'কেরাত কন্ডিশন টাইপ',
    'Kerat Condition': 'কেরাত কন্ডিশন',
    'Total Subject': 'মোট বিষয়',
    'If you need to divide the total number by a number other than the specified number, enter it in the box below and click the Save button.':
      'উল্লেখিত সংখ্যা ব্যতীত অন্য কোনো সংখ্যা দ্বারা যদি মোট নাম্বার ভাগ দেওয়ার প্রয়োজন হয়, তাহলে নিচের বক্সে তা লিখে সেইভ বাটনে ক্লিক করুন।',
    SL: 'নম্বর',
    '>=1': '>=১',
    '>=2': '>=২',
    '>=3': '>=৩',
    '>=4': '>=৪',
    '>=5': '>=৫',
    '>=6': '>=৬',
    'Division-1': 'ডিভিশন-১',
    'Division-2': 'ডিভিশন-২',
    'Division-3': 'ডিভিশন-৩',
    'Division-4': 'ডিভিশন-৪',
    'Division-5': 'ডিভিশন-৫',
    'Division-6': 'ডিভিশন-৬',
    'Division Arabic-1': 'ডিভিশন আরবী-1',
    'Division Arabic-2': 'ডিভিশন আরবী-২',
    'Division Arabic-3': 'ডিভিশন আরবী-৩',
    'Division Arabic-4': 'ডিভিশন আরবী-৪',
    'Division Arabic-5': 'ডিভিশন আরবী-৫',
    'Division Arabic-6': 'ডিভিশন আরবী-৬',
    'Exam Condition': 'পরীক্ষার কন্ডিশন',
    'Deposit Costs Report': 'জমা খরচের রিপোর্ট',
    'Field 1': 'ফিল্ড ১',
    'Field 2': 'ফিল্ড ২',
    'Field 3': 'ফিল্ড ৩',
    'Field 4': 'ফিল্ড ৪',
    'Field 5': 'ফিল্ড ৫',
    'Field 6': 'ফিল্ড ৬',
    'Residential Name': 'আবাসন',
    'Date Of Birth': 'জন্ম তারিখ',
    Position: 'অবস্থান',
  };

  return (key) =>
    currectLanguage === 'bn' ? englishToBangla[key] || key : key;
};

export default useTranslate;
