import { useSelector } from "react-redux";

const useTranslate = () => {
  const { currectLanguage } = useSelector((state) => state.language);

  const englishToBangla = {
    Home: "হোম",
    Student: "শিক্ষার্থী",
    "Book List": "বুক লিস্ট",
    "Status": "স্ট্যাটাস",
    "SMS ID": "এসএমএস আইডি",
    "Phone Number": "ফোন নম্বর",
    "Success and Error": "সাকসেস এবং এরোর",
    Staff: "স্টাফ",
    Exam: "পরীক্ষা",
    Libery: "লাইব্রেরি",
    Others: "অন্যান্য",
    SMS: "এসএমএস",
    Balance: "ব্যালেন্স",
    Book: "কিতাব",
    "Section": "ক্লাস গ্রুপ",
    "All Students": "সকল শিক্ষার্থী",
    "Students Report": "শিক্ষার্থী রিপোর্ট",
    "Student Vacation": "শিক্ষার্থী ছুটি",
    "Group Distribution": "শিক্ষার্থী গ্রুপ সেটিং",
    "Certificate of Attestation": "প্রত্যয়ন পত্র",
    "Online Admission": "অনলাইন ভর্তি",
    "Sub Class": "সাব ক্লাস",
    "New/Old": "নতুন/পুরাতন",
    "Excel File Name": "এক্সেল ফাইলের নাম",
    "Export students data": "শিক্ষার্থীদের তথ্য সেভ করুন",
    "Data Export": "ডাটা এক্সপোর্ট",
    "Send single and multiple SMS": "একক এবং একাধিক এসএমএস পাঠান",
    "SMS Sending Form": "মেসেজ প্রেরণ ফর্ম",
    "Missing or invalid data provided": "অনুপস্থিত বা অবৈধ তথ্য সরবরাহ করা হয়েছে",
    "Buy SMS": "মেসেজ কিনতে",
    "Buy SMS": "মেসেজ কিনতে",
    "1st Month": "১ম মাস",
    "2nd Month": "২য় মাস",
    "3rd Month": "৩য় মাস",
    "4th Month": "৪র্থ মাস",
    "5th Month": "৫ম মাস",
    "6th Month": "৬ষ্ঠ মাস",
    "7th Month": "৭ম মাস",
    "8th Month": "৮ম মাস",
    "9th Month": "৯ম মাস",
    "10th Month": "১০ম মাস",
    "11th Month": "১১তম মাস",
    "12th Month": "১২তম মাস",
    "Enter name or number for 1st Month": "১ম মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 2nd Month": "২য় মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 3rd Month": "৩য় মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 4th Month": "৪র্থ মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 5th Month": "৫ম মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 6th Month": "৬ষ্ঠ মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 7th Month": "৭ম মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 8th Month": "৮ম মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 9th Month": "৯ম মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 10th Month": "১০ম মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 11th Month": "১১তম মাসের নাম্বার বা নাম লিখুন",
    "Enter name or number for 12th Month": "১২তম মাসের নাম্বার বা নাম লিখুন",
    "Months list table": "মাসের তালিকা টেবিল",
    "Months create": "মাস তৈরি",
    "Session is required": "সেশন প্রয়োজন",
    "Class is required": "ক্লাস প্রয়োজন",
    "1st Month name is required": "১ম মাস প্রয়োজন",
    "2nd Month name is required": "২য় মাস প্রয়োজন",
    "3rd Month name is required": "৩য় মাস প্রয়োজন",
    "4th Month name is required": "৪র্থ মাস প্রয়োজন",
    "5th Month name is required": "৫ম মাস প্রয়োজন",
    "6th Month name is required": "৬ষ্ঠ মাস প্রয়োজন",
    "7th Month name is required": "৭ম মাস প্রয়োজন",
    "8th Month name is required": "৮ম মাস প্রয়োজন",
    "9th Month name is required": "৯ম মাস প্রয়োজন",
    "10th Month name is required": "১০ম মাস প্রয়োজন",
    "11th Month name is required": "১১তম মাস প্রয়োজন",
    "12th Month name is required": "১২তম মাস প্রয়োজন",
    Setting: "সেটিংস",
    "Sahara IT": "সাহারা আইটি",
    Sahara: "সাহারা",
    IT: "আইটি",
    "Last Modified": "সর্বশেষ পরিবর্তিত",
    Last: "সর্বশেষ",
    Modified: "পরিবর্তিত",
    "Update Student Report": "ছাত্র রিপোর্ট আপডেট",
    Today: "আজ",
    "Last Week": "শেষ সপ্তাহ",
    "Last Month": "শেষ মাস",
    "Date Added": "তারিখ যোগ",
    "User Based Report": "ব্যবহারকারী ভিত্তিক প্রতিবেদন",
    "Report": "রিপোর্ট",
    "Preview": "পূর্বরূপ",
    "General Information": "সাধারণ তথ্য",
    "User Reports": "ব্যবহারকারী রিপোর্ট",
    "User Types": "ব্যবহারকারীর ধরন",
    Date: "তারিখ",
    Added: "যোগ করা হয়েছে",
    "Newest First": "নতুন থেকে শুরু",
    "Oldest First": "পুরাতন থেকে শুরু",
    "Create Type": "ছুটির ধরন তৈরি করুন",
    "From Time": "সময় থেকে",
    "Be Time": "সময় হতে",
    Search: "অনুসন্ধান",
    "Mother Name": "মাতার নাম",
    Years: "সাল",
    "User Status": "ব্যবহারকারীর অবস্থা",
    Active: "অ্যাক্টিভ",
    InActive: "ইনঅ্যাক্টিভ",
    Both: "উভয়",
    Notification: "বিজ্ঞপ্তি",
    "Start Year": "সাল হতে",
    "End Year": "সাল পর্যন্ত",
    Online: "অনলাইন",
    "Set Status": "অবস্থা নির্ধারণ",
    Settings: "সেটিংস",
    "Share Your Opinion": "আপনার মতামত শেয়ার করুন",
    Class: "শ্রেণী",
    "Class/Jamaat": "শ্রেণী/জামাত",
    English: "ইংরেজী",
    "Add Class": "ক্লাস যোগ করুন",
    Save: "সংরক্ষণ করুন",
    "Add New": "নতুন যোগ করুন",
    Serial: "সিরিয়াল",
    Sections: "সাব ক্লাস",
    Bangla: "বাংলা",
    Arabic: "আরবি",
    "Create month names": "মাসের নাম তৈরি করুন",
    "Update month names": "মাসের নাম আপডেট করুন",
    User: "ইউজার",
    Filter: "ফিল্টার",
    "Not Admitted students": "ভর্তি না হওয়া শিক্ষার্থী",
    "Admitted students": "ভর্তিকৃত শিক্ষার্থী ",
    "Complete Admission": "ভর্তি সম্পূর্ন করুন",
    "Admitted Students List": "ভর্তিকৃত ছাত্র তালিকা",
    "Not Admitted Students List": "ভর্তি না হওয়া শিক্ষার্থীদের তালিকা",
    "Student Name": "শিক্ষার্থীর নাম",
    "Father Name": "পিতার নাম",
    Mobile: "মোবাইল",
    "Entry Date": "এন্টি তারিখ",
    Session: "শিক্ষাবর্ষ",
    Vacation: "ছুটি",
    Single: "একক",
    "Class Based": "ক্লাস ভিত্তিক",
    Vacation: "ছুটি",
    "Admission Class": "ভর্তি ইচ্ছুক ক্লাস",
    "Admission Serial": "ভর্তি সিরিয়াল",
    "Financial Condition": "আর্থিক অবস্থা",
    "Living Condition": "আবাসন অবস্থা",
    "Admission Type": "ভর্তির ধরণ",
    Select: "নির্বাচন করুন",
    "Admission Details": "ভর্তির ফরম",
    "Request already in progress. Please wait...":
      "অনুরোধ ইতিমধ্যে প্রক্রিয়াধীন। অনুগ্রহ করে অপেক্ষা করুন...",
    "Information Added Successfully": "তথ্য যুক্ত করা হয়েছে।",
    Employee: "কর্মচারী",
    "Admitted Teacher List": "যোগদেয়া কর্মীদের তালিকা",
    "Not Admitted Teacher List": "যোগ না দেয়া কর্মীদের তালিকা",
    Account: "একাউটিং",
    "User ID": "ইউজার আইডি",
    "Book Name": "কিতাবের নাম",
    "Add Book": "কিতাব যোগ করুন",
    "Student's English Name": "শিক্ষার্থীর ইংরেজি নাম",
    "Start User ID": "ইউজার আইডি হতে",
    "End User ID": "ইউজার আইডি পর্যন্ত",
    "Enter start user id": "ব্যবহারকারী আইডি হতে লিখুন",
    "Enter end user id": "ব্যবহারকারী আইডি পর্যন্ত লিখুন",
    "Teacher Code": "শিক্ষক কোড",
    "Father Name": "বাবার নাম",
    "Date of join": "যোগদানের তারিখ",
    "Inter your date of join": "যোগদানের তারিখ যোগ করুন",
    "Inter your result devision": "ফলাফল বিভাগ যোগ করুন",
    "Inter your passted date": "পাসের তারিখ যোগ করুন",
    "Inter your qualification": "যোগ্যতা যোগ করুন",
    "Inter your exam board name": "পররীক্ষার বোর্ডের নাম যোগ করুন",
    "Inter your experience": "অভিজ্ঞতা যোগ করুন",
    "Employee Details": "কর্মচারী বিবরণ",
    "Enter image": "ছবি প্রবেশ করান",
    "Serial Title": "শিরোনাম সিরিয়াল",
    "Result Devision": "ফলাফল বিভাগ",
    Year: "পাসের বছর",
    "Exam Board Name": "পররীক্ষার বোর্ডের নাম",
    "Teacher Info Update": "শিক্ষক তথ্য আপডেট",
    "Designation List": "পদবী তালিকা",
    "Create Designation": "পদবী তৈরি করুন",
    "Update Designation": "পদবী আপডেট করুন",
    "Enter new designation": "নতুন পদবি লিখুন",
    "Teacher Register": "শিক্ষক নিবন্ধন",
    "From Date": "তারিখ থেকে ",
    "Up to date": "তারিখ পর্যন্ত",
    Account: "একাউটিং",
    Mobile1: "মোবাইল ১",
    Name: "নাম",
    Gender: "লিঙ্গ",
    Action: "অ্যাকশন",
    Register: "রেজিস্টার সম্পুর্ণ করুন",
    Experience: "অভিজ্ঞতা",
    Qualification: "যোগ্যতা",
    Designation: "পদবী",
    Comment: "মন্তব্য",
    UserHolidayNo: "ছুটির নাম্বার",
    ID: "নাম্বার",
    "User Code": "ইউজার কোড",
    "Student Code": "ছাত্রের কোড",
    "Date of entry": "এন্ট্রি তারিখ",
    "Type of vacation": "ছুটির ধরণ",
    "Date of leave": "ছুটির তারিখ",
    "Holiday time": "ছুটির সময়",
    "Start Date of leave": "ছুটির তারিখ হতে",
    "End Date of leave": "ছুটির তারিখ পর্যন্ত",
    "Start Time of leave": "ছুটির সময় হতে",
    "End Time of leave": "ছুটির সময় পর্যন্ত",
    "Select Time": "সময় নির্বাচন করুন",
    "Student ID": "শিক্ষার্থীর আইডি",
    "Marhala/Class": "মারহালা/ক্লাস",
    "English & Arobi Name": "ইংরেজি এবং আরবি নাম",
    "List of holidays": "ছুটির তালিকা",
    "Vacation type list": "ছুটির তালিকার ধরণ",
    "Type of holiday create": "তৈরি ছুটির ধরণ",
    "Type of holiday update": "আপডেট ছুটির ধরণ",
    "Enter type of vacation": "ছুটির ধরণ লিখুন",
    "Update Student Vacation Info": "শিক্ষার্থীদের ছুটির তথ্য আপডেট করুন",
    "Create Student Vacation Info": "শিক্ষার্থীদের ছুটির তথ্য তৈরি করুন",
    "Edit Vacation": "ছুটি আপডেট করুন",
    "Create Vacation": "ছুটি তৈরি করুন",
    "Vacation type": "ছুটির ধরণ",
    Jamaat: "জামা’য়াত",
    Jamaat: "জামা’য়াত",
    Relationship: "সম্পর্ক",
    Varient: "প্রকার",
    Type: "ধরন",
    Remark: "মন্তব্য",
    "Institution Name (Bangla)": "প্রতিষ্ঠানের নাম (বাংলা)",
    "Institution Name (Arabic)": "প্রতিষ্ঠানের নাম (আরবি)",
    "Institution Name (English)": "প্রতিষ্ঠানের নাম (ইংরেজি)",
    "Enter Institution Name (Bangla)": "প্রতিষ্ঠানের নাম লিখুন",
    "Enter Institution Name (Arabic)": "প্রতিষ্ঠানের আরবি নাম লিখুন",
    "Enter Institution Name (English)": "প্রতিষ্ঠানের ইংরেজি নাম লিখুন",
    "Address (Bengali)": "ঠিকানা (বাংলা)",
    "Address (Arabic)": "ঠিকানা (আরবি)",
    "Address (English)": "ঠিকানা (ইংরেজি)",
    "Enter Address (Bengali)": "আরবি ঠিকানা লিখুন",
    "Enter Address (Arabic)": "আরবি ঠিকানা লিখুন",
    "Enter Address (English)": "ইংরেজি ঠিকানা লিখুন",
    Village: "গ্রাম",
    "Post Office": "ডাকঘর",
    "Police Station": "থানা",
    District: "জেলা",
    "Arabic Village": "গ্রাম (আরবি)",
    "Arabic Post Office": "ডাকঘর (আরবি)",
    "Arabic Police Station": "থানা (আরবি)",
    "Arabic District": "জেলা (আরবি)",
    "Enter Village": "গ্রামের নাম লিখুন",
    "Enter Post Office": "ডাকঘরের নাম লিখুন",
    "Enter Police Station": "থানার নাম লিখুন",
    "Enter District": "জেলার নাম লিখুন",
    "Enter Arabic Village": "গ্রামের আরবি নাম লিখুন",
    "Enter Arabic Post Office": "ডাকঘরের আরবি নাম লিখুন",
    "Enter Arabic Police Station": "থানার আরবি নাম লিখুন",
    "Enter Arabic District": "জেলার আরবি নাম লিখুন",
    "Contact Number": "ফোন নম্বর",
    "Arabic Contact Number": "ফোন নম্বর (আরবি)",
    "SMS Mobile": "এসএমএস মোবাইল",
    "Email Address": "ইমেইল ঠিকানা",
    "Enter Contact Number": "ফোন নম্বর লিখুন",
    "Enter Arabic Contact Number": "আরবি ফোন নম্বর লিখুন",
    "Enter SMS Mobile Number": "এসএমএস মোবাইল নম্বর লিখুন",
    "Enter Email Address": "ইমেইল ঠিকানা লিখুন",
    "Institution Code": "প্রতিষ্ঠান কোড",
    Elhaq: "ইলহাক",
    "Enter Institution Code": "প্রতিষ্ঠান কোড লিখুন",
    "Enter Elhaq": "ইলহাক লিখুন",
    "Principal Name": "প্রিন্সিপালের নাম",
    "Najem Name": "নাজেমের নাম",
    "Accountant Name": "হিসাবরক্ষকের নাম",
    "Enter Principal Name": "প্রিন্সিপালের নাম লিখুন",
    "Enter Najem Name": "নাজেমের নাম লিখুন",
    "Enter Accountant Name": "হিসাবরক্ষকের নাম লিখুন",
    "Institution Names": "প্রতিষ্ঠানের নামসমূহ",
    Addresses: "ঠিকানাসমূহ",
    "Location Information": "অবস্থান সম্পর্কিত তথ্য",
    "Contact Information": "যোগাযোগের তথ্য",
    "Institution Details": "প্রতিষ্ঠানের বিস্তারিত",
    "Institution Logo Upload": "প্রতিষ্ঠানের লোগো আপলোড",
    Signatories: "দায়িত্বপ্রাপ্ত ব্যক্তিবর্গ",
    "Institution Name is required": "প্রতিষ্ঠানের নাম আবশ্যক",
    "Exam Board Name is require": "পরীক্ষা বোর্ডের নাম আবশ্যক",
    "Result devision is require": "ফলাফল বিভাগ আবশ্যক",
    "Character Report": "চারিত্রিক রিপোর্ট",
    "No.": "ক্র: নং",
    "Total students": "মোট শিক্ষার্থী",
    "Total teachers": "মোট শিক্ষক",
    "Total donor member": "মোট দাতা সদস্য",
    "Total owed": "মোট পাওনা",
    "Class-based student distribution": "শ্রেণি ভিত্তিক শিক্ষার্থী বন্টন",
    Calendar: "ক্যালেন্ডার",
    "Pay Now": "এখনই পেমেন্ট করুন",
    "Number of students by class": "ক্লাস ভিত্তিক শিক্ষার্থীর সংখ্যা",
    "Presence and absence": "উপস্থিতি ও অনুপস্থিতি",
    "Number of students according to the previous academic year":
      "বিগত শিক্ষাবর্ষ অনুযায়ী শিক্ষার্থী সংখ্যা",
    Dashboard: "ড্যাশবোর্ড",
    "Teacher Staff": "শিক্ষক কর্মচারী",
    "Result": "ফলাফল",
    "Board Exam": "বোর্ড পরীক্ষা",
    "Darul Ikama": "দারুল ইকামা",
    "Accounting": "অ্যাকাউন্টিং",
    "Donation": "দান অনুদান",
    "Library": "পাঠাগার",
    "Others": "অন্যান্য",
    "Help": "সাহায্য",
    "Month Name": "মাসের নাম",
    "Institution Information": "প্রতিষ্ঠানের তথ্য",
    "Parents": "অভিভাবক",
    "All Users": "সকল ইউজার",
    "Mobile Number": "মোবাইল নম্বর",
    "Message Type": "মেসেজের ধরন",
    "Enter mobile number": "মোবাইল নম্বর লিখুন",
    "Message Template": "মেসেজ টেমপ্লেট",
    "Message": "মেসেজ",
    "Enter your message": "আপনার মেসেজ লিখুন",
    "765": "৭৬৫",
    "Characters typed": "অক্ষর টাইপ করা হয়েছে",
    "next SMS from 67 chars": "৬৭টি অক্ষর থেকে পরবর্তী এসএমএস",
    "1 SMS": "১ মেসেজ",
    "70 Char/SMS": "৭০ অক্ষর/মেসেজ",
    "Send SMS": "মেসেজ পাঠান",
    "Reset SMS": "মেসেজ রিসেট",
    "To create a list of mobile numbers by typing": "টাইপ করে মোবাইল নাম্বারের তালিকা তৈরি করতে",
    "SMS purchase form": "এসএমএস ক্রয়ের ফর্ম",
    "Please enter the amount of SMS you would like to receive below.": "যত টাকার এসএমএস নিতে চান, তত টাকা নিচে উল্লেখ করুন",
    "Amount of Taka": "টাকার পরিমাণ",
    "The amount of money must be paid.": "টাকার পরিমাণ অবশ্যই দিতে হবে",
    "Enter the amount of money (eg: 100).": "টাকার পরিমাণ লিখুন (যেমন: ১০০)",
    "SMS can be purchased from a minimum of 100 Taka.": "সর্বনিম্ন ১০০ টাকা থেকে এসএমএস ক্রয় করা যাবে",
    "SMS Rate: 0.30 Taka per SMS Approximately 333 SMS can be sent for 100 Taka": "এসএমএস এর দর: প্রতি এসএমএস ০.৩০ টাকা ১০০ টাকায় প্রায় ৩৩৩ টি এসএমএস পাঠানো যাবে",
    "Message Name": "মেসেজ নাম",
    "Enter new message name": "নতুন মেসেজ নাম লিখুন",
    "Invalid Bangladeshi mobile prefix": "অবৈধ বাংলাদেশী মোবাইল প্রিফিক্স",
    "Mobile number must be 11 digits": "মোবাইল নম্বর অবশ্যই ১১ সংখ্যার হতে হবে",
    "SMS Templates": "মেসেজ টেমপ্লেট",
    "SMS Buy": "মেসেজ কিনুন",
    "This number already exists": "এই নম্বরটি ইতিমধ্যেই বিদ্যমান।",
    "Write only in Bengali.": "শুধুমাত্র বাংলা ভাষায় লিখুন।",
    "Write only in English.": "শুধুমাত্র ইংরেজি ভাষায় লিখুন।",

  };

  return (key) =>
    currectLanguage === "bn" ? englishToBangla[key] || key : key;
};

export default useTranslate;
